"use client";
import Image from "next/image";
import { motion, type Variants } from "motion/react";
import { UsernameForm } from "@/components/shared/username-form";

const containerVariants: Variants = {
    hidden: { opacity: 0 },
    show: {
        opacity: 1, 
        transition: {
            staggerChildren: 0.15,
            delayChildren: 0.1,
        },
    },
};

const itemVariants: Variants = {
    hidden: { opacity: 0, y: 20 },
    show: {
        opacity: 1,
        y: 0,
        transition: { duration: 0.6, ease: "easeOut" },
    },
};

const mockupVariants: Variants = {
    hidden: { opacity: 0, y: 40, scale: 0.99 },
    show: {
        opacity: 1,
        y: 0,
        scale: 1,
        transition: { duration: 0.8, ease: [0.16, 1, 0.3, 1] },
    },
};

export default function LandingHero() {
    return (
        <motion.section 
            className="flex flex-col items-center justify-center"
            variants={containerVariants}
            initial="hidden"
            animate="show"
        >
            <div className="text-center max-w-xl mt-8 mb-6">
                <motion.h1 
                    variants={itemVariants}
                    className="text-4xl md:text-5xl font-semibold leading-[1.1] tracking-tight font-display px-4"
                >
                    From GitHub to Portfolio. Instantly.
                </motion.h1>
                
                <motion.p 
                    variants={itemVariants}
                    className="text-balance mt-4 text-base md:text-lg text-muted-foreground md:leading-relaxed px-4 md:px-0"
                >
                    Showcase your work with stunning, customizable dev portfolio
                    templates and let AI handle the copy.
                </motion.p>
            </div>
            
            <motion.div variants={itemVariants} className="w-full flex justify-center">
                <UsernameForm />
            </motion.div>
            
            <motion.p 
                variants={itemVariants}
                className="text-center text-muted-foreground text-xs leading-relaxed mt-4"
            >
                Read-only access. We don&apos;t touch your private data.
            </motion.p>
            
            <motion.div 
                variants={mockupVariants}
                className="relative w-full flex justify-center mb-4 mt-12 md:mb-12 px-0 md:px-8"
            >
                <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                    <div className="w-[70%] md:w-[50%] aspect-square rounded-full bg-primary/6 blur-[80px] md:blur-[150px]" />
                </div>

                <div
                    className="w-full max-w-5xl flex justify-center items-center p-6 sm:p-12 md:p-16 lg:p-24 rounded-2xl md:rounded-4xl bg-cover bg-center bg-no-repeat"
                    style={{ backgroundImage: "url('/bg-grid-two.png')" }}
                >
                    <Image
                        src="/Safari Dark.png"
                        alt="Portfolio preview — Linus Torvalds generated by GitXhibit"
                        width={0}
                        height={0}
                        sizes="100vw"
                        className="block w-full h-auto rounded-lg md:rounded-xl shadow-2xl"
                        draggable={false}
                    />
                </div>
            </motion.div>
        </motion.section>
    );
}